format = """
$directory\
$username\
$hostname\
$git_branch\
$git_state\
$git_status\
$git_commit\
$aws\
$nodejs\
$python\
$rust\
$golang\
$docker_context\
$package\
$line_break\
$character"""

# Right side of the prompt
right_format = "$cmd_duration $time $battery"

add_newline = true

[character]
success_symbol = "[ğŸˆâ€â¬›->](bold #8D8442)"
error_symbol = "[ğŸˆâ€â¬›->](bold #822F36)"
vicmd_symbol = "[ğŸˆâ€â¬›â®](bold #D56920)"

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 15
style = 'bold #822F36'
discharging_symbol = 'ğŸ’€ '

[[battery.display]]
threshold = 30
style = 'bold #D56920'

[[battery.display]]
threshold = 100

[directory]
style = "#9D7CD8 bold"
format = "[ ]($style)[$path]($style) "
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " "
read_only_style = "#822F36"

[username]
style_user = "#8D8442 bold"
style_root = "#822F36 bold"
format = '[\[$user\]]($style)' #Remove '\[' or '\]' if you do not want brackets
show_always = true

[hostname]
format = "[@$hostname:](#8D8442 bold)"
ssh_only = true

[git_branch]
symbol = " "
style = "#9D7CD8 bold"
format = '[$symbol$branchÂ·]($style)'

[git_status]
style = "#9D7CD8 bold"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_commit]
style = "#9D7CD8 bold"
commit_hash_length = 4
tag_symbol = 'ğŸ”– '

[git_state]
style = "#9D7CD8 bold"
format = '\([$state( $progress_current of $progress_total)]($style)\) '

[nodejs]
symbol = "â¬¢ "
style = "#8D8442"
format = "[$symbol($version)]($style) "

[lua]
format = 'via [ğŸŒ• $version](bold #9D7CD8) '

[python]
symbol = " "
style = "#9D7CD8"
format = "[$symbol($version)]($style) "

[rust]
symbol = "ğŸ¦€ "
style = "#822F36"
format = "[$symbol($version)]($style) "

[golang]
symbol = " "
style = "#A88E71"
format = "[$symbol($version)]($style) "

[docker_context]
symbol = "ğŸ³ "
style = "#9D7CD8 bold"
format = "[$symbol$context]($style) "

[terraform]
format = '[ğŸğŸ’¨ $workspace]($style) '

[aws]
format = "on [$symbol($profile)(($region))]($style) "
symbol = "  "
style = "bold #D56920"
disabled = true
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'

[azure]
disabled = false
format = "on [$symbol($username)]($style) "
symbol = "ó° … "
style = "#9D7CD8 bold"

[package]
symbol = "ğŸ“¦ "
style = "#D56920 bold"
format = "[$symbol$version]($style) "

[cmd_duration]
disabled = false
show_notifications = true
min_time_to_notify = 100
min_time = 1
show_milliseconds = true
format = '[\(â± $duration\)]($style) '
style = "#D56920 bold"

[time]
disabled = false
time_format = "%e-%B-%Y %R"                            # Hour:Minute Format
style = "bg:#202825"
format = '[[  $time ](fg:#A88E71 bg:#202825)]($style)'

[memory_usage]
symbol = "ó°› "
format = '\[$symbol[$ram( | $swap)]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[status]
format = '[$symbol$common_meaning$signal_name]($style) '
style = '#9D7CD8'
symbol = 'âŒ'
success_symbol = 'ğŸŸ¢'
not_executable_symbol = 'ğŸš«'
not_found_symbol = 'ğŸ”'
sigint_symbol = 'ğŸ§±'
signal_symbol = 'âš¡'
disabled = false
